---
- name: Find remote content
  find:
    paths: "{{ tt_dest_dir }}"
    recurse: true
    file_type: any
    hidden: true
  register: _remote

- name: Establish lists of local and remote content
  set_fact:
    _remote_paths: "{{ _remote| json_query('files[].path') | map('relpath', tt_dest_dir) }}"
    _local_paths: "{{_files_to_rename|json_query('[].new_path') | union(
      _files_to_not_rename|union(_dirs)|json_query('[].path')) |
      map('relpath', tt_src_dir) }}"

- name: Ensure remote content is removed
  file:
    path: "{{ tt_dest_dir }}/{{ remotepath }}"
    state: absent
  loop: "{{ _remote_paths|difference(_local_paths) }}"
  loop_control:
    loop_var: remotepath
  register: tt_result_delete
