---
- name: Ensure required variables are set
  assert:
    that: "{{ varname }} is defined"
    fail_msg: "Required variable '{{ varname }}' is not defined, exiting."
    quiet: true
  loop:
    - tt_src_dir
    - tt_dest_dir
  loop_control:
    loop_var: varname

- name: "Find all local content in {{ tt_src_dir }}"
  become: false
  connection: local
  find:
    paths: "{{ tt_src_dir }}"
    recurse: true
    hidden: true
    file_type: any
  register: _local

- name: Ensure that we have some files at least
  assert:
    that:
      - _local.files|count > 0
    fail_msg: "{{ tt_src_dir }} does not exist or has no content"
    quiet: true

- name: Create list of all files
  set_fact:
    _files: "{{ _local | json_query('files[?!isdir]') }}"

- name: Include file renaming tasks
  include_tasks: rename.yml

#- debug: var=_files

#FIXME things go wrong in here!!!
- name: Include validation tasks
  include_tasks: validate.yml
  when: tt_validate|length > 0

#- debug: var=_files

- name: Establish list of directories, templates, and files
  set_fact:
    _dirs: "{{ _local | json_query('files[?isdir]') }}"
    _template_files: "{{ _files | selectattr('path', 'regex', tt_template_pattern) }}"
    # A bit of duplication but this way we can have just a single set_fact task
    _copy_files: "{{ _files | difference (_files | selectattr('path', 'regex', tt_template_pattern)) }}"

#- debug: var=_template_files

- name: "Ensure directories are available at {{ tt_dest_dir }}"
  file:
    path: "{{ tt_dest_dir ~ '/' ~ ( dir.path | relpath(tt_src_dir))  }}"
    state: directory
    mode: "{{ tt_dir_mode | default(dir.mode) }}"
    owner: "{{ tt_owner | default(omit) }}"
    group: "{{ tt_group | default(omit) }}"
  loop: "{{ _dirs }}"
  loop_control:
    loop_var: dir
    label: "{{ dir.path | relpath(tt_src_dir) }}"
  register: tt_result_dirs

- name: Ensure files are templated
  template:
    src: '{{ file.path }}'
    dest: "{{ tt_dest_dir ~ '/' ~ ( file.new_path|default(file.path) | relpath(tt_src_dir)) }}"
    mode: "{{ tt_file_mode | default(file.mode) }}"
    owner: "{{ tt_owner | default(omit) }}"
    group: "{{ tt_group | default(omit) }}"
    validate: "{{ file.validate | default(omit) }}"
  loop: "{{ _template_files }}"
  loop_control:
    loop_var: file
    label: " {{ file.new_path|default(file.path) }} => {{ tt_dest_dir ~ '/' ~ ( file.new_path|default(file.path) | relpath(tt_src_dir)) }}"
    #label: " {{ file.new_path|default(file.path) }} => {{ file.new_path|default(file.path) | relpath(tt_src_dir)  }}"
  register: tt_result_templates

- name: Ensure remainder files are copied as-is
  copy:
    src: '{{ file.path }}'
    dest: "{{ tt_dest_dir ~ '/' ~ ( file.new_path|default(file.path) | relpath(tt_src_dir)) }}"
    mode: "{{ tt_file_mode | default(file.mode) }}"
    owner: "{{ tt_owner | default(omit) }}"
    group: "{{ tt_group | default(omit) }}"
    validate: "{{ file.validate | default(omit) }}"
  loop: "{{ _copy_files }}"
  loop_control:
    loop_var: file
    label: " {{ file.path }} => {{ tt_dest_dir ~ '/' ~ ( file.new_path|default(file.path) | relpath(tt_src_dir)) }}"
  register: tt_result_files

- name: Include deletion tasks
  include_tasks: delete.yml
  when: tt_delete|bool

- name: Set changed status
  set_fact:
    tt_changed: "{{ [
      tt_result_dirs.changed,
      tt_result_templates.changed,
      tt_result_files.changed,
      tt_result_delete.changed|default(false)
      ] | max }}"
