---
- name: Initialise variables
  ansible.builtin.set_fact:
    _files_to_rename: []
    _files_to_not_rename: []

# FIXME do this more efficiently, if possible without looping over all files...
- name: Create list of files to rename
  ansible.builtin.set_fact:
    _files_to_rename: "{{ _files_to_rename | default([]) | union(
       [file] | selectattr('path', 'regex', tt_strip_pattern) |
       map('combine', {'new_path': file.path | regex_replace(tt_strip_pattern, '') } )
      ) }}"
  loop: "{{ _files }}"
  loop_control:
    loop_var: file
    label: "{{ file.path }}"

- name: Create list of files to not rename
  ansible.builtin.set_fact:
    _files_to_not_rename: "{{ _files | rejectattr('path', 'in', _files_to_rename | json_query('[?new_path].path')) }}"

- name: Create list of all of files, with rename info
  ansible.builtin.set_fact:
    _files: "{{ _files_to_rename | union(_files_to_not_rename) }}"
